/* ============================================================
   catalog.js — the problem index, the concept graph, and lazily
   fetched problem and solution files.

   data/index.json is generated by scripts/build-index.mjs and
   carries metadata only: enough to list, search and filter every
   problem without downloading any of them. A problem's statement
   arrives when you open it, and its answer key only when you
   submit.

   That split is also the only answer-hiding a static site can
   honestly offer: the key is not in the page you are reading, so
   seeing it has to be a decision rather than an accident.
   ============================================================ */

const Catalog = (() => {

  const INDEX_URL    = 'data/index.json';
  const CONCEPTS_URL = 'data/concepts.json';

  const TYPES = [
    { id: 'mcq',     label: 'Multiple choice', note: 'One right answer.' },
    { id: 'multi',   label: 'Select all',      note: 'Several right answers, partial credit.' },
    { id: 'numeric', label: 'A number',        note: 'A figure, within a tolerance.' },
    { id: 'short',   label: 'Short answer',    note: 'A word or a flag.' },
    { id: 'order',   label: 'Put in order',    note: 'Arrange the steps.' },
    { id: 'match',   label: 'Match pairs',     note: 'Pair the two columns.' },
    { id: 'predict', label: 'Predict output',  note: 'Say exactly what it prints.' },
    { id: 'locate',  label: 'Find the bug',    note: 'Click the offending line.' },
    { id: 'code',    label: 'Write code',      note: 'Compiled and run against tests.' },
  ];
  const TYPE_BY_ID = Object.fromEntries(TYPES.map(t => [t.id, t]));

  let index    = [];
  let byId     = {};
  let concepts = {};
  let loadError = null;

  const fullCache = new Map();
  const solCache  = new Map();

  async function init() {
    const [idx, con] = await Promise.all([
      fetchJson(INDEX_URL),
      fetchJson(CONCEPTS_URL),
    ]);
    if (idx.ok) {
      index = Array.isArray(idx.data) ? idx.data : (idx.data.problems || []);
      byId = Object.fromEntries(index.map(p => [p.id, p]));
    } else {
      loadError = idx.error;
    }
    concepts = con.ok ? con.data : {};
    return { index, concepts, loadError };
  }

  async function fetchJson(url) {
    try {
      const res = await fetch(url, { cache: 'no-cache' });
      if (!res.ok) return { ok: false, error: `${res.status} ${res.statusText}` };
      return { ok: true, data: await res.json() };
    } catch (err) {
      /* Opening index.html straight off disk blocks fetch in some browsers.
         That is a legitimate way to look at the page, so it is reported
         rather than thrown. */
      return { ok: false, error: String(err && err.message || err) };
    }
  }

  /* ---------------- listing ---------------- */

  const all = () => index;
  const meta = id => byId[id] || null;

  function list(filter = {}) {
    const q = String(filter.q || '').trim().toLowerCase();
    const terms = q ? q.split(/\s+/) : [];

    return index.filter(p => {
      if (filter.topic      && p.topic      !== filter.topic)      return false;
      if (filter.difficulty && p.difficulty !== filter.difficulty) return false;
      if (filter.type       && p.type       !== filter.type)       return false;

      if (filter.status) {
        const r = Store.record(p.id);
        if (filter.status === 'flagged') {
          const due = r.reviewOn && r.reviewOn <= Store.todayISO();
          if (!r.flagged && !due) return false;
        } else if (r.status !== filter.status) return false;
      }

      if (terms.length) {
        const hay = `${p.title} ${p.topic} ${p.type} ${(p.tags || []).join(' ')}`.toLowerCase();
        if (!terms.every(t => hay.includes(t))) return false;
      }
      return true;
    });
  }

  /* Difficulty, then title — so a topic reads as a path through it rather
     than as whatever order the files happened to be walked in. */
  const ORDER = { beginner: 0, intermediate: 1, advanced: 2 };
  function sorted(rows) {
    return [...rows].sort((a, b) =>
      (ORDER[a.difficulty] ?? 9) - (ORDER[b.difficulty] ?? 9) ||
      a.title.localeCompare(b.title));
  }

  /* ---------------- one problem ---------------- */

  const pathFor     = p => `problems/${p.topic}/${p.id}.json`;
  const solPathFor  = id => `solutions/${id}.json`;

  async function get(id) {
    if (fullCache.has(id)) return fullCache.get(id);
    const m = byId[id];
    if (!m) return null;
    const res = await fetchJson(pathFor(m));
    if (!res.ok) return null;
    /* The index is generated from the problem file, so where they disagree the
       file is right — but id, topic and difficulty are what progress is keyed
       and scored on, so they come from the index to stay consistent with it. */
    const full = { ...res.data, id: m.id, topic: m.topic, difficulty: m.difficulty, type: m.type };
    fullCache.set(id, full);
    return full;
  }

  async function solution(id) {
    if (solCache.has(id)) return solCache.get(id);
    const res = await fetchJson(solPathFor(id));
    if (!res.ok) return null;
    solCache.set(id, res.data);
    return res.data;
  }

  /* ---------------- concepts ---------------- */

  const concept = id => concepts[id] || null;
  const allConcepts = () => Object.entries(concepts).map(([id, c]) => ({ id, ...c }));

  /* Prerequisites are transitive: a concept names what it needs, and what it
     needs names what *it* needs. Returned deepest-first, which is reading
     order — you cannot start in the middle of a chain.

     Cycles are tolerated rather than trusted: content.test.mjs fails the build
     on one, but a cycle here must not hang the page. */
  function chain(rootId) {
    const out = [];
    const seen = new Set();
    const visiting = new Set();

    (function walk(id) {
      if (seen.has(id) || visiting.has(id) || !concepts[id]) return;
      visiting.add(id);
      for (const need of concepts[id].needs || []) walk(need);
      visiting.delete(id);
      seen.add(id);
      out.push({ id, ...concepts[id] });
    })(rootId);

    return out;
  }

  /* Every concept a problem rests on, in reading order, each carrying the
     problem's own sentence on why it is needed here. */
  function prereqsFor(problem) {
    const why = {};
    for (const p of problem.prereqs || []) why[p.concept] = p.why || '';
    const seen = new Set();
    const out = [];
    for (const p of problem.prereqs || []) {
      for (const c of chain(p.concept)) {
        if (seen.has(c.id)) continue;
        seen.add(c.id);
        out.push({ ...c, why: why[c.id] || '', direct: Object.hasOwn(why, c.id) });
      }
    }
    return out;
  }

  /* How much of a concept's reading list you have ticked off. */
  function readProgress(conceptId) {
    const c = concepts[conceptId];
    const total = (c && c.readings || []).length;
    if (!total) return { read: 0, total: 0, fraction: 1 };
    let read = 0;
    for (let i = 0; i < total; i += 1) if (Store.hasRead(conceptId, i)) read += 1;
    return { read, total, fraction: read / total };
  }

  return {
    init, all, meta, list, sorted, get, solution,
    concept, allConcepts, chain, prereqsFor, readProgress,
    TYPES, TYPE_BY_ID,
    get loadError() { return loadError; },
  };
})();
