/* ============================================================
   catalog.js — the problem index, the concept graph, and lazily
   fetched problem and solution files.

   data/index.json is generated by scripts/build-index.mjs and
   carries metadata only: enough to list, search and filter every
   problem without downloading any of them. A problem's statement
   arrives when you open it, and its answer key only when you
   submit.

   That split is also the only answer-hiding a static site can
   honestly offer: the key is not in the page you are reading, so
   seeing it has to be a decision rather than an accident.
   ============================================================ */

const Catalog = (() => {

  const INDEX_URL     = 'data/index.json';
  const CONCEPTS_URL  = 'data/concepts.json';
  const TRACKS_URL    = 'data/tracks.json';
  const WEEKLY_URL    = 'data/weekly.json';
  const RESOURCES_URL = 'data/resources.json';

  const TYPES = [
    { id: 'mcq',     label: 'Multiple choice', note: 'One right answer.' },
    { id: 'multi',   label: 'Select all',      note: 'Several right answers, partial credit.' },
    { id: 'numeric', label: 'A number',        note: 'A figure, within a tolerance.' },
    { id: 'short',   label: 'Short answer',    note: 'A word or a flag.' },
    { id: 'order',   label: 'Put in order',    note: 'Arrange the steps.' },
    { id: 'match',   label: 'Match pairs',     note: 'Pair the two columns.' },
    { id: 'predict', label: 'Predict output',  note: 'Say exactly what it prints.' },
    { id: 'locate',  label: 'Find the bug',    note: 'Click the offending line.' },
    { id: 'code',    label: 'Write code',      note: 'Compiled and run against tests.' },
  ];
  const TYPE_BY_ID = Object.fromEntries(TYPES.map(t => [t.id, t]));

  let index     = [];
  let byId      = {};
  let concepts  = {};
  let tracks    = [];
  let weekly    = { weeks: [] };
  let resources = { topics: {} };
  let loadError = null;

  const fullCache = new Map();
  const solCache  = new Map();

  async function init() {
    const [idx, con, trk, wk, res] = await Promise.all([
      fetchJson(INDEX_URL),
      fetchJson(CONCEPTS_URL),
      fetchJson(TRACKS_URL),
      fetchJson(WEEKLY_URL),
      fetchJson(RESOURCES_URL),
    ]);
    if (idx.ok) {
      index = Array.isArray(idx.data) ? idx.data : (idx.data.problems || []);
      byId = Object.fromEntries(index.map(p => [p.id, p]));
    } else {
      loadError = idx.error;
    }
    concepts = con.ok ? con.data : {};
    /* These three are extras: the site is perfectly usable without them, so a
       missing or malformed file leaves the feature out rather than breaking
       the page. */
    tracks    = trk.ok && Array.isArray(trk.data) ? trk.data : [];
    weekly    = wk.ok && wk.data && Array.isArray(wk.data.weeks) ? wk.data : { weeks: [] };
    resources = res.ok && res.data && res.data.topics ? res.data : { topics: {} };

    return { index, concepts, tracks, weekly, resources, loadError };
  }

  async function fetchJson(url) {
    try {
      const res = await fetch(url, { cache: 'no-cache' });
      if (!res.ok) return { ok: false, error: `${res.status} ${res.statusText}` };
      return { ok: true, data: await res.json() };
    } catch (err) {
      /* Opening index.html straight off disk blocks fetch in some browsers.
         That is a legitimate way to look at the page, so it is reported
         rather than thrown. */
      return { ok: false, error: String(err && err.message || err) };
    }
  }

  /* ---------------- listing ---------------- */

  const all = () => index;
  const meta = id => byId[id] || null;

  function list(filter = {}) {
    const q = String(filter.q || '').trim().toLowerCase();
    const terms = q ? q.split(/\s+/) : [];

    return index.filter(p => {
      if (filter.topic      && p.topic      !== filter.topic)      return false;
      if (filter.difficulty && p.difficulty !== filter.difficulty) return false;
      if (filter.type       && p.type       !== filter.type)       return false;
      if (filter.lane       && (p.lane || 'core') !== filter.lane)  return false;

      if (filter.status) {
        const r = Store.record(p.id);
        if (filter.status === 'flagged') {
          const due = r.reviewOn && r.reviewOn <= Store.todayISO();
          if (!r.flagged && !due) return false;
        } else if (r.status !== filter.status) return false;
      }

      if (terms.length) {
        const hay = `${p.title} ${p.topic} ${p.type} ${(p.tags || []).join(' ')}`.toLowerCase();
        if (!terms.every(t => hay.includes(t))) return false;
      }
      return true;
    });
  }

  /* Difficulty, then title — so a topic reads as a path through it rather
     than as whatever order the files happened to be walked in. */
  const ORDER = { beginner: 0, intermediate: 1, advanced: 2 };
  function sorted(rows) {
    return [...rows].sort((a, b) =>
      (ORDER[a.difficulty] ?? 9) - (ORDER[b.difficulty] ?? 9) ||
      a.title.localeCompare(b.title));
  }

  /* ---------------- one problem ---------------- */

  const pathFor     = p => `problems/${p.topic}/${p.id}.json`;
  const solPathFor  = id => `solutions/${id}.json`;

  async function get(id) {
    if (fullCache.has(id)) return fullCache.get(id);
    const m = byId[id];
    if (!m) return null;
    const res = await fetchJson(pathFor(m));
    if (!res.ok) return null;
    /* The index is generated from the problem file, so where they disagree the
       file is right — but id, topic and difficulty are what progress is keyed
       and scored on, so they come from the index to stay consistent with it. */
    const full = { ...res.data, id: m.id, topic: m.topic, difficulty: m.difficulty, type: m.type };
    fullCache.set(id, full);
    return full;
  }

  async function solution(id) {
    if (solCache.has(id)) return solCache.get(id);
    const res = await fetchJson(solPathFor(id));
    if (!res.ok) return null;
    solCache.set(id, res.data);
    return res.data;
  }

  /* ---------------- concepts ---------------- */

  const concept = id => concepts[id] || null;
  const allConcepts = () => Object.entries(concepts).map(([id, c]) => ({ id, ...c }));

  /* Prerequisites are transitive: a concept names what it needs, and what it
     needs names what *it* needs. Returned deepest-first, which is reading
     order — you cannot start in the middle of a chain.

     Cycles are tolerated rather than trusted: content.test.mjs fails the build
     on one, but a cycle here must not hang the page. */
  function chain(rootId) {
    const out = [];
    const seen = new Set();
    const visiting = new Set();

    (function walk(id) {
      if (seen.has(id) || visiting.has(id) || !concepts[id]) return;
      visiting.add(id);
      for (const need of concepts[id].needs || []) walk(need);
      visiting.delete(id);
      seen.add(id);
      out.push({ id, ...concepts[id] });
    })(rootId);

    return out;
  }

  /* Every concept a problem rests on, in reading order, each carrying the
     problem's own sentence on why it is needed here. */
  function prereqsFor(problem) {
    const why = {};
    for (const p of problem.prereqs || []) why[p.concept] = p.why || '';
    const seen = new Set();
    const out = [];
    for (const p of problem.prereqs || []) {
      for (const c of chain(p.concept)) {
        if (seen.has(c.id)) continue;
        seen.add(c.id);
        out.push({ ...c, why: why[c.id] || '', direct: Object.hasOwn(why, c.id) });
      }
    }
    return out;
  }

  /* How much of a concept's reading list you have ticked off. */
  function readProgress(conceptId) {
    const c = concepts[conceptId];
    const total = (c && c.readings || []).length;
    if (!total) return { read: 0, total: 0, fraction: 1 };
    let read = 0;
    for (let i = 0; i < total; i += 1) if (Store.hasRead(conceptId, i)) read += 1;
    return { read, total, fraction: read / total };
  }

  /* ---------------- tracks ----------------

     A track is an ordered list of problem ids. Ids that are not in the catalog
     are dropped rather than rendered as dead rows, so a track can name a
     problem that has not been written yet without breaking the page. */

  function allTracks() {
    return tracks.map(t => ({
      ...t,
      problems: (t.problems || []).filter(id => byId[id]),
      missing: (t.problems || []).filter(id => !byId[id]).length,
    }));
  }

  const track = id => allTracks().find(t => t.id === id) || null;

  /* Solved count and the next unsolved problem, which is the only thing a
     track really has to answer. */
  function trackProgress(t) {
    const rows = (t.problems || []).map(id => ({ id, meta: byId[id], record: Store.record(id) }));
    const done = rows.filter(r => r.record.status === 'solved').length;
    const touched = rows.filter(r => r.record.status !== 'unsolved').length;
    const next = rows.find(r => r.record.status !== 'solved') || null;

    /* Three states, and the middle one has to be earned. A track nobody has
       opened was being labelled "in progress", which made every track look
       half-done and the label worth nothing. */
    const state = !rows.length ? 'empty'
      : done === rows.length ? 'completed'
      : touched > 0 ? 'attempted'
      : 'not-started';

    /* Resuming beats starting: a problem opened and not finished is where the
       reader actually left off, so it outranks the next untouched one. */
    const resume = rows.find(r => r.record.status === 'attempted')
      || rows.find(r => r.record.status === 'read')
      || next;

    return {
      done, touched, total: rows.length, rows, next, resume, state,
      fraction: rows.length ? done / rows.length : 0,
    };
  }

  const TRACK_STATE_LABEL = {
    'not-started': 'Not started',
    attempted: 'Attempted',
    completed: 'Completed',
    empty: 'Empty',
  };

  /* ---------------- the week's problem ----------------

     The latest entry whose Monday has arrived. Entries dated in the future are
     ignored, so the schedule can run ahead of today without giving anything
     away. */
  function thisWeek(today = Store.todayISO()) {
    const past = (weekly.weeks || [])
      .filter(w => w.from && w.from <= today && byId[w.problem])
      .sort((a, b) => a.from.localeCompare(b.from));
    if (!past.length) return null;
    const w = past[past.length - 1];
    return { ...w, meta: byId[w.problem], weekOf: w.from };
  }

  /* ---------------- resources ---------------- */

  const topicResources = topicId => (resources.topics || {})[topicId] || null;
  const allResources = () => Object.entries(resources.topics || {}).map(([id, r]) => ({ id, ...r }));

  /* ---------------- concepts, the other way round ----------------

     A problem names the concepts it rests on. The reading list wants the
     reverse — which exercises practise this concept — so that reading a
     chapter has a visible next step rather than being its own reward. Built
     from the index, which already carries each problem's prereq concept ids,
     so no problem file has to be fetched. Cached, because the reading view
     calls it once per concept. */
  let reverseIndex = null;

  function problemsForConcept(conceptId) {
    if (!reverseIndex) {
      reverseIndex = {};
      for (const p of index) {
        for (const c of p.prereqs || []) {
          (reverseIndex[c] = reverseIndex[c] || []).push(p);
        }
      }
      for (const list of Object.values(reverseIndex)) {
        list.sort((a, b) =>
          (ORDER[a.difficulty] ?? 9) - (ORDER[b.difficulty] ?? 9) ||
          a.title.localeCompare(b.title));
      }
    }
    return reverseIndex[conceptId] || [];
  }

  /* Unread / part-read / read, plus how much of the whole list is done. The
     status is per concept, which is the unit someone actually works through. */
  function readStatus(conceptId) {
    const p = readProgress(conceptId);
    if (!p.total) return { ...p, state: 'none' };
    if (p.read === 0) return { ...p, state: 'unread' };
    if (p.read >= p.total) return { ...p, state: 'read' };
    return { ...p, state: 'partly' };
  }

  const READ_STATE_LABEL = {
    none: 'No readings',
    unread: 'Unread',
    partly: 'Partly read',
    read: 'Read',
  };

  /* ---------------- what to do next ----------------

     The dashboard's main action, and the one question worth answering well:
     of eighty-five problems, which one now. In order of preference:

       1. something already started, in the track furthest along
       2. the next problem in that track
       3. the first problem of the first track not yet begun
       4. anything unsolved at all, easiest first
       5. nothing - everything is solved

     Returning the reason as well as the problem, because "picking up where you
     left off" and "starting a new track" deserve different wording. */
  function nextUp() {
    const open = allTracks()
      .map(t => ({ t, p: trackProgress(t) }))
      .filter(x => x.p.total && x.p.state !== 'completed');

    const started = open
      .filter(x => x.p.state === 'attempted')
      .sort((a, b) => b.p.fraction - a.p.fraction)[0];

    if (started) {
      const row = started.p.resume;
      if (row && row.meta) {
        return {
          meta: row.meta,
          track: started.t,
          progress: started.p,
          reason: row.record.status === 'unsolved' ? 'next-in-track' : 'resume',
        };
      }
    }

    const fresh = open.find(x => x.p.state === 'not-started');
    if (fresh && fresh.p.next && fresh.p.next.meta) {
      return { meta: fresh.p.next.meta, track: fresh.t, progress: fresh.p, reason: 'new-track' };
    }

    /* No track has anything left, but the catalogue might - tracks do not
       have to cover every problem. */
    const loose = sorted(index.filter(p => Store.record(p.id).status !== 'solved'))[0];
    if (loose) return { meta: loose, track: null, progress: null, reason: 'loose' };

    return null;
  }

  /* ---------------- counts ----------------

     Everything the copy on the page wants to say about how much is here. A
     sentence that says "nine topics" is a sentence that is wrong the next time
     a topic is added, so no view spells a number out. Counted over the index
     rather than over Store.TOPICS, so a topic with nothing in it yet is not
     advertised. */
  function counts() {
    const topics = new Set();
    const difficulties = new Set();
    const types = new Set();
    const langs = new Set();
    let code = 0;
    let minutes = 0;

    for (const p of index) {
      topics.add(p.topic);
      difficulties.add(p.difficulty);
      types.add(p.type);
      minutes += Number(p.estimate) || 0;
      if (p.type === 'code') {
        code += 1;
        for (const l of p.langs || []) langs.add(l);
      }
    }

    let readings = 0;
    for (const c of Object.values(concepts)) readings += (c.readings || []).length;
    for (const r of Object.values(resources.topics || {})) readings += (r.resources || []).length;

    return {
      problems: index.length,
      topics: topics.size,
      difficulties: difficulties.size,
      types: types.size,
      code,
      languages: langs.size,
      concepts: Object.keys(concepts).length,
      readings,
      tracks: tracks.length,
      minutes,
    };
  }

  return {
    init, all, meta, list, sorted, get, solution,
    concept, allConcepts, chain, prereqsFor, readProgress,
    allTracks, track, trackProgress, thisWeek, topicResources, allResources,
    counts, nextUp, problemsForConcept, readStatus,
    TYPES, TYPE_BY_ID, TRACK_STATE_LABEL, READ_STATE_LABEL,
    get loadError() { return loadError; },
  };
})();
