/* ============================================================
   runners/browsercpp.js — C++ on this device, with nothing
   installed and nothing paid for.

   Clang 20.1.2 compiled to WebAssembly, running in a worker in
   this tab. 90 MB of compiler, fetched the first time somebody
   presses Run on a C++ problem and cached afterwards, and then
   roughly a second per compile and a few milliseconds per case.

   The shape of a run:

     compile worker   long-lived, holds the compiler
     run worker       one per case, terminated on timeout or
                      cancellation and never reused

   This answers in exactly the shape the local runner and the
   hosted proxy answer in, so nothing downstream can tell which
   of the three produced a verdict — except that it says so,
   because being told where your program ran is the difference
   between a service outage and a mistake of your own.

   What it cannot do is in js/cxx/toolchain.js and is taken
   seriously: no exceptions, no sanitizers, and wasm32 integer
   and pointer sizes. data/cxx-support.json says which problems
   are certified for it, and that file is generated by compiling
   every one of them rather than by anybody's judgement.
   ============================================================ */

const BrowserCpp = (() => {

  /* Where this file was loaded from, captured while the script is still
     executing. The site loads its modules as plain <script> tags, so
     import.meta does not exist here — it is a syntax error in a classic
     script — and the worker URLs have to be resolved against something.
     This works the same on a user page, a project page and localhost. */
  const HERE = (() => {
    const self = document.currentScript && document.currentScript.src;
    return self ? new URL('.', self).href : new URL('js/runners/', location.href).href;
  })();
  const workerUrl = name => new URL(`../cxx/${name}`, HERE).href;

  const COMPILE_MS = 60_000;   /* the first one includes 63 MB of WebAssembly */
  const RUN_MS = 5_000;        /* per case, matching the local runner */
  const MAX_SOURCE = 256 * 1024;

  /* Loaded once, lazily: the list of problems whose own reference solution
     was compiled and run with this toolchain and got every case right. */
  let support = null;
  let supportTried = false;

  async function loadSupport() {
    if (supportTried) return support;
    supportTried = true;
    try {
      const res = await fetch(new URL('../../data/cxx-support.json', HERE).href,
        { cache: 'no-cache' });
      if (res.ok) support = await res.json();
    } catch { /* offline, or the file is not there; treated as "nothing certified" */ }
    return support;
  }

  /* Whether this *browser* could run C++ at all, which is a different
     question from whether a given problem should. */
  function capable() {
    return typeof Worker !== 'undefined'
      && typeof WebAssembly !== 'undefined'
      && typeof WebAssembly.compile === 'function';
  }

  async function supportsProblem(problemId) {
    if (!capable()) return false;
    const s = await loadSupport();
    if (!s) return false;
    return (s.browser || []).includes(problemId);
  }

  async function reasonFor(problemId) {
    const s = await loadSupport();
    return (s && s.nativeOnly && s.nativeOnly[problemId]) || null;
  }

  const toolchain = () => (support && support.toolchain) || null;

  /* ---------------- the compile worker ---------------- */

  let compiler = null;      /* the Worker */
  let ready = false;        /* has it finished downloading and preparing? */
  let readying = null;      /* the in-flight init, shared by concurrent callers */
  const listeners = new Set();

  /* Anyone who wants to watch the download. Returns an unsubscribe. */
  function onProgress(fn) {
    listeners.add(fn);
    return () => listeners.delete(fn);
  }
  const announce = p => { for (const fn of [...listeners]) { try { fn(p); } catch { /* a bad listener is not our problem */ } } };

  let lastProgress = null;
  const progress = () => lastProgress;

  function spawnCompiler() {
    if (compiler) return compiler;
    compiler = new Worker(workerUrl('compile.worker.js'), { type: 'module' });
    compiler.onerror = () => { /* surfaced through the pending promise instead */ };
    return compiler;
  }

  /* Downloads and prepares the toolchain. Safe to call repeatedly. */
  function prepare() {
    if (ready) return Promise.resolve();
    if (readying) return readying;

    readying = new Promise((resolve, reject) => {
      let w;
      try { w = spawnCompiler(); } catch (err) {
        reject(new Error(`could not start the compiler worker: ${err.message}`));
        return;
      }

      const onMessage = e => {
        const m = e.data || {};
        if (m.type === 'progress') {
          lastProgress = m;
          announce(m);
          return;
        }
        if (m.type === 'ready') {
          w.removeEventListener('message', onMessage);
          w.removeEventListener('error', onError);
          ready = true;
          lastProgress = { loaded: 1, total: 1, percent: 100, stage: 'ready' };
          announce(lastProgress);
          resolve();
          return;
        }
        if (m.type === 'failed') {
          w.removeEventListener('message', onMessage);
          w.removeEventListener('error', onError);
          reject(new Error(m.error));
        }
      };
      const onError = ev => {
        w.removeEventListener('message', onMessage);
        w.removeEventListener('error', onError);
        /* A module worker that will not load at all: almost always a
           missing file, a wrong path on a project-page deployment, or a
           server sending the wrong MIME type for a .js module. */
        reject(new Error(ev.message
          || 'the compiler worker failed to load — check that vendor/cxx is deployed'));
      };

      w.addEventListener('message', onMessage);
      w.addEventListener('error', onError);
      w.postMessage({ type: 'init' });
    });

    readying.catch(() => {
      /* A failed preparation must not poison every later attempt. */
      teardown();
    }).finally(() => { readying = null; });

    return readying;
  }

  function teardown() {
    if (compiler) { try { compiler.terminate(); } catch { /* already gone */ } }
    compiler = null;
    ready = false;
  }

  let nextId = 1;

  function compileSource(source, { signal } = {}) {
    return new Promise((resolve, reject) => {
      const id = nextId++;
      const w = spawnCompiler();
      let settled = false;

      const finish = fn => (...a) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        w.removeEventListener('message', onMessage);
        if (signal) signal.removeEventListener('abort', onAbort);
        fn(...a);
      };
      const ok = finish(resolve);
      const bad = finish(reject);

      const timer = setTimeout(() => {
        /* The compiler itself has hung. Nothing short of terminating it will
           help, and it has to be rebuilt before the next attempt. */
        teardown();
        bad(new Error('the compiler stopped responding'));
      }, COMPILE_MS);

      const onMessage = e => {
        const m = e.data || {};
        if (m.id !== id) return;
        if (m.type === 'compiled') ok(m);
        else if (m.type === 'failed') bad(new Error(m.error));
      };
      const onAbort = () => {
        teardown();
        bad(new DOMException('cancelled', 'AbortError'));
      };

      w.addEventListener('message', onMessage);
      if (signal) {
        if (signal.aborted) { onAbort(); return; }
        signal.addEventListener('abort', onAbort, { once: true });
      }
      w.postMessage({ type: 'compile', id, source });
    });
  }

  /* ---------------- one case, in its own worker ---------------- */

  function runOne(bytes, stdin, { runMs = RUN_MS, signal } = {}) {
    return new Promise(resolve => {
      let worker;
      try {
        worker = new Worker(workerUrl('run.worker.js'), { type: 'module' });
      } catch (err) {
        resolve(crashResult(`could not start a run worker: ${err.message}`));
        return;
      }

      let settled = false;
      const started = Date.now();
      const done = result => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        if (signal) signal.removeEventListener('abort', onAbort);
        try { worker.terminate(); } catch { /* already gone */ }
        resolve(result);
      };

      /* The whole reason a case gets its own worker. A wasm loop with no
         allocation and no syscall cannot be interrupted any other way. */
      const timer = setTimeout(() => done({
        stdout: '', stderr: '', exit: -1, signal: 'SIGKILL',
        timedOut: true, ms: Date.now() - started, sanitizer: false,
      }), runMs);

      const onAbort = () => done({
        stdout: '', stderr: '', exit: -1, signal: 'SIGKILL',
        timedOut: false, cancelled: true, ms: Date.now() - started, sanitizer: false,
      });

      worker.onmessage = e => {
        const m = e.data || {};
        if (m.type === 'done') done({ ...m.result, ms: Date.now() - started });
        else if (m.type === 'failed') done(crashResult(m.error, Date.now() - started));
      };
      worker.onerror = ev => done(crashResult(ev.message || 'the run worker failed', Date.now() - started));

      if (signal) {
        if (signal.aborted) { onAbort(); return; }
        signal.addEventListener('abort', onAbort, { once: true });
      }

      /* A copy per worker: the buffer is transferred, so the original would
         be detached after the first case. */
      const copy = bytes.slice();
      worker.postMessage({ type: 'run', bytes: copy, stdin: stdin || '' }, [copy.buffer]);
    });
  }

  const crashResult = (message, ms = 0) => ({
    stdout: '', stderr: String(message), exit: -1, signal: null,
    timedOut: false, ms, sanitizer: false,
  });

  /* ---------------- the runner interface ---------------- */

  /* One compile, then one fresh instance per case — the same contract the
     native runner has, so a problem means the same thing on both. */
  async function run(source, cases, { runMs = RUN_MS, signal, onStage } = {}) {
    const say = s => { if (onStage) onStage(s); };

    if (!capable()) return down('this browser cannot run WebAssembly in a worker');
    if (String(source).length > MAX_SOURCE) {
      return down(`the source is larger than ${Math.round(MAX_SOURCE / 1024)} KB`);
    }

    try {
      if (!ready) say('downloading');
      await prepare();
    } catch (err) {
      if (err && err.name === 'AbortError') return cancelled();
      return down(err.message);
    }

    say('compiling');
    let built;
    try {
      built = await compileSource(source, { signal });
    } catch (err) {
      if (err && err.name === 'AbortError') return cancelled();
      return down(err.message);
    }

    if (!built.ok || !built.bytes) {
      return {
        lang: 'cpp', backend: 'browsercpp',
        compile: { ok: false, stdout: '', stderr: built.stderr || '', ms: 0, timedOut: false },
        cases: [],
      };
    }

    say('running');
    const results = [];
    for (const c of (cases || [])) {
      if (signal && signal.aborted) return cancelled();
      /* eslint-disable-next-line no-await-in-loop -- cases are deliberately
         sequential: a fresh instance each, and an early abort should not
         leave four more workers running. */
      const r = await runOne(built.bytes, c.stdin, { runMs, signal });
      if (r.cancelled) return cancelled();
      results.push(r);
    }

    return {
      lang: 'cpp', backend: 'browsercpp',
      compile: { ok: true, stdout: '', stderr: built.stderr || '', ms: 0, timedOut: false },
      cases: results,
    };
  }

  const down = why => ({
    lang: 'cpp', backend: 'browsercpp',
    compile: { ok: false, stdout: '', stderr: '', ms: 0, timedOut: false },
    cases: [], judgeDown: true,
    judgeError: `The in-browser compiler could not be used: ${why}.`,
  });

  const cancelled = () => ({
    lang: 'cpp', backend: 'browsercpp',
    compile: { ok: false, stdout: '', stderr: '', ms: 0, timedOut: false },
    cases: [], judgeDown: true, cancelled: true,
    judgeError: 'Stopped. Nothing was recorded, and your code is as you left it.',
  });

  return {
    capable, supportsProblem, reasonFor, loadSupport, toolchain,
    prepare, onProgress, progress, teardown, run,
    get ready() { return ready; },
    /* Exposed for the browser tests, which drive a compile without a page. */
    compileSource, runOne,
    TOTAL_MB: 90,
  };
})();
